# =============================================================================
# Pipeline Template
# =============================================================================
# Copy this file to your repo's .github/workflows/pipeline.yml and update
# the values below for your service.
#
# Required repository secrets:
#   - PKG_READ_TOKEN: GitHub Packages read token for scoped packages
#   - GCP_WORKLOAD_IDENTITY_PROVIDER: (for deploy stages)
#   - GCP_SERVICE_ACCOUNT: (for deploy stages)
# =============================================================================

name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    uses: medyca/public/.github/workflows/reusable-full-pipeline.yml@main
    with:
      # TODO: Update these values for your service
      service-name: my-service         # Change to your service name
      org: my-org                      # Change to your GitHub organization
      infra-repo: my-org/my-infra      # Change to your infrastructure repo
      port: "3000"                     # Change to your service port
      deploy-staging: true
      deploy-production: false         # Set to true when ready for production deploys
    secrets: inherit
