# =============================================================================
# Medyca Pipeline Template
# =============================================================================
# Copy this file to your repo's .github/workflows/pipeline.yml and update
# the service-name and port values.
#
# Required repository secrets:
#   - PKG_READ_TOKEN: GitHub Packages read token for @medyca/* packages
#   - GCP_WORKLOAD_IDENTITY_PROVIDER: (for deploy stages)
#   - GCP_SERVICE_ACCOUNT: (for deploy stages)
# =============================================================================

name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    uses: medyca/public/.github/workflows/reusable-full-pipeline.yml@main
    with:
      # TODO: Update these values for your service
      service-name: mbe-authentication  # Change to your service name
      port: "3034"                      # Change to your service port
      deploy-staging: true
      deploy-production: false          # Set to true when ready for production deploys
    secrets: inherit
